# Generated by Django 5.1.4 on 2024-12-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upload_notes", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uploadnote",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="uploadnote",
            name="image",
        ),
        migrations.AddField(
            model_name="uploadnote",
            name="description",
            field=models.TextField(default="No description"),
        ),
        migrations.AddField(
            model_name="uploadnote",
            name="file",
            field=models.FileField(
                default="path/to/default/file.pdf", upload_to="uploads/"
            ),
        ),
    ]
