# Generated by Django 5.1.4 on 2024-12-13 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("to_do_list", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="completed",
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.AddField(
            model_name="task",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(default="2024-12-13"),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
